apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: front-hpa
spec:
  targetCPUUtilizationPercentage: 50
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front
