apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: project
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: group10
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MYSQL_DATABASE
              value: project
            - name: MYSQL_PASSWORD
              value: group10
            - name: MYSQL_USER
              value: backend
          image: mongo:latest
          name: mongodb
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: my-dbs
      restartPolicy: Always
      volumes:
        - name: my-dbs
          persistentVolumeClaim:
            claimName: my-dbs
status: {}
