apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - args:
            - "--ignore-db-dir=lost+found"
          env:
            - name: MYSQL_DATABASE
              value: project
            - name: MYSQL_PASSWORD
              value: group10
            - name: MYSQL_ROOT_PASSWORD
              value: group10
            - name: MYSQL_USER
              value: backend
          image: mysql:5.7
          name: mysql
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: my-dbs
            - mountPath: /data/application/mysql_init.sql
              name: mysql-claim1
      restartPolicy: Always
      volumes:
        - name: my-dbs
          persistentVolumeClaim:
            claimName: my-dbs
        - name: mysql-claim1
          persistentVolumeClaim:
            claimName: mysql-claim1

status: {}
